// <auto-generated />
namespace Week8ClassLibrary2022.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClubContetCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClubContetCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202211140917449_Club Contet Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
