// <auto-generated />
namespace Week8ClassLibrary2022.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seedingclubsandclubevents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedingclubsandclubevents));
        
        string IMigrationMetadata.Id
        {
            get { return "202211141009091_seeding clubs and club events"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
